# SPDX-License-Identifier: MIT
# Copyright (c) 2021 Volodymyr Turanskyy

from testing_utils import *

from microbit import *
import music

music.set_tempo(5, 130)
t = music.get_tempo()
music.play('c4')
music.play(['c', 'd', 'e'])
music.pitch(500)
music.stop()
music.reset()

music.play(music.DADADADUM)
sleep(1000)
music.play(music.ENTERTAINER)
sleep(1000)
music.play(music.PRELUDE)
sleep(1000)
music.play(music.ODE)
sleep(1000)
music.play(music.NYAN)
sleep(1000)
music.play(music.RINGTONE)
sleep(1000)
music.play(music.FUNK)
sleep(1000)
music.play(music.BLUES)
sleep(1000)
music.play(music.BIRTHDAY)
sleep(1000)
music.play(music.WEDDING)
sleep(1000)
music.play(music.FUNERAL)
sleep(1000)
music.play(music.PUNCHLINE)
sleep(1000)
music.play(music.PYTHON)
sleep(1000)
music.play(music.BADDY)
sleep(1000)
music.play(music.CHASE)
sleep(1000)
music.play(music.BA_DING)
sleep(1000)
music.play(music.WAWAWAWAA)
sleep(1000)
music.play(music.JUMP_UP)
sleep(1000)
music.play(music.JUMP_DOWN)
sleep(1000)
music.play(music.POWER_UP)
sleep(1000)
music.play(music.POWER_DOWN)
sleep(1000)
